; Sakti S S Naibaho 1306412773
; Riansyah Sumajaya 1306447436
; Limas Baginta	    1306368690

data_Button      EQU P1
button0 Bit data_Button.0
button1 Bit data_Button.1
button2 Bit data_Button.2
button3 Bit data_Button.3
button4 Bit data_Button.4
button5 Bit data_Button.5
button6 Bit data_Button.6
button7 Bit data_Button.7

START:
			;CHESS CLOCK AKAN BERJALAN DI ALAMAT MEMORI
MOV R0,#5H		;MENIT PEMAIN A BERLOKASI DI R0
MOV R1,#0H		;DETIK DIGIT PERTAMA PEMAIN A BERLOKASI DI R1
MOV R2,#0H		;DETIK DIGIT KEDUA PEMAIN A BERLOKASI DI R2
MOV R5,#5H		;MENIT PEMAIN B BERLOKASI DI R5
MOV R6,#0H		;DETIK DIGIT PERTAMA PEMAIN B BERLOKASI DI R6
MOV R7,#0H		;DETIK DIGIT KEDUA PEMAIN B BERLOKASI DI R7
JNB P1.0,M_A		;JIKA KEYPAD A DISET, MAKA CLOCK YANG MULAI DULUAN ADALAH PEMAIN A
JNB P1.1,M_B		;JIKA KEYPAD B DISET, MAKA CLOCK YANG MULAI DULUAN ADALAH PEMAIN B
SJMP START		;JIKA KEYPAD A&B BELUM DISET, MAKA CLOCK TIDAK BERGERAK SAMPAI KEYPAD 			 A&B DISET

;COMMAND PEMAIN A
M_A:				;FUNGSI MENIT PEMAIN A
	MOV R1,#0FFH
	SJMP S1_A
	
S1_A_0:	
	INC R0			;FUNGSI BILA DETIK DIGIT 1 A BERNILAI 0
	DJNZ R0,M_A
	MOV R1,#0FFH
	SJMP S1_A
	SJMP SELESAI
	
S1_A:				;FUNGSI DETIK DIGIT 1 PEMAIN A
	INC R1
	ACALL S2_A_1
	DJNZ R1,S1_A
	MOV R2,#0H
	ACALL DELAY
	JB P1.0,S2_B_1
	MOV R2,#09H
	
S2_A_0:				;FUNGSI BILA DETIK DIGIT 2 A BERNILAI 0
	ACALL DELAY
	JB P1.0,S2_B_1
	DJNZ R2,S2_A_0
	SJMP S1_A_0

S2_A_1:				;FUNGSI DETIK DIGIT 2 PEMAIN A TAHAP I(PEMINJAMAN S1 KE S2)
	MOV A,#0H
	MOV B,R2
	CJNE A,B,S2_A_2
	MOV R2,#9H
	DEC R1
	
S2_A_2:				;FUNGSI DETIK DIGIT 2 PEMAIN A TAHAP II(PEMINJAMAN M KE S2)
	MOV A,#0FFH
	MOV B,R1
	CJNE A,B,S2_A_3
	MOV R1,#5H
	DEC R0
	
S2_A_3:				;FUNGSI DETIK DIGIT 2 PEMAIN A TAHAP III(PENCETAKAN NILAI S2)
	JB P1.0,S2_B_1
	DJNZ R2,S2_A_1
	RET

;COMMAND PEMAIN B
M_B:				;FUNGSI MENIT PEMAIN B
	MOV R6,#0FFH
	SJMP S1_B
	
S1_B_0:				;FUNGSI BILA DETIK DIGIT 1 B BERNILAI 0
	INC R5
	DJNZ R5,M_B
	MOV R6,#0FFH
	SJMP S1_B
	SJMP SELESAI
S1_B:				;FUNGSI DETIK DIGIT 1 PEMAIN B
	INC R6
	ACALL S2_B_1
	DJNZ R6,S1_B
	MOV R7,#0H
	ACALL DELAY
	JB P1.1,S2_B_1
	MOV R7,#09H
	
S2_B_0:				;FUNGSI BILA DETIK DIGIT 2 B BERNILAI 0
	ACALL DELAY
	JB P1.1,S2_A_1
	DJNZ R7,S2_B_0
	SJMP S1_B_0

S2_B_1:				;FUNGSI DETIK DIGIT 2 PEMAIN B TAHAP I(PEMINJAMAN S1 KE S2)
	MOV A,#0H
	MOV B,R7
	CJNE A,B,S2_B_2
	MOV R7,#9H
	DEC R6
	
S2_B_2:				;FUNGSI DETIK DIGIT 2 PEMAIN A TAHAP II(PEMINJAMAN M KE S2)
	MOV A,#0FFH
	MOV B,R6
	CJNE A,B,S2_B_3
	MOV R6,#5H
	DEC R5
	
S2_B_3:				;FUNGSI DETIK DIGIT 2 PEMAIN A TAHAP III(PENCETAKAN NILAI S2)
	JB P1.1,S2_A_1
	DJNZ R7,S2_B_1
	RET

;FUNGSI DELAY
DELAY:	MOV A,#2
	SETB TR0		;MEMBUAT Timer 0 MULAI MENGHITUNG
	CJNE A,TL0,$		;JIKA TL0 BELUM BERNILAI 2, TERUS MELAKUKAN INSTRUKSI INI
	
SELESAI:			;FUNGSI UNTUK MENGAKHIRI PROGRAM (BILA SALAH SATU CLOCK 					 HABIS)
